### ISSUE TITLE
nicht auswählbar nach Installation!

### ISSUE THREAD

**Issue by sfx12** [oveleon/contao-advanced-form#1]
Hallo,

ich sehe nach der Installation, links nicht das Menü "advanced form" im Backend, wie bei euren screenshots in der doku ?

Contao Ver. 4.9.11 - PHP 7.4

**Comment by doishub** [comment]
Hallo sfx12,

die Readme wurde hier leider aus der [alten Erweiterung](https://github.com/oveleon/contao-advanced-form-bundle) übernommen und stimmt nicht mit der neuen Vorgehensweise überein. Ich gebe das intern einmal weiter, damit wir die Doku hier entsprechend anpassen. 

Mit diesem (neuen) Bundle werden die Seiten direkt im Formular selber definiert.

**Comment by zoglo** [comment]
Guten Abend @sfx12 ,

die Readme wurde mit einer *englischen* Dokumentation versehen. Diese sollte die Grundlagen und die Einrichtung erklären.
