### ISSUE TITLE
Bedingung mit größer oder kleiner Operatoren

### ISSUE THREAD

**Issue by Shoekrates** [oveleon/contao-advanced-form#10]
Hallo!
Irgendwie bekomme ich den bedingten Seitenwechsel nicht zum Laufen, wenn ich auf einen Wert mit größer (>) oder kleiner (<) bzw. größer gleich (>=) oder kleiner gleich (<=) prüfe.
Meine Bedingung: 
`$feldname <= '10'`
Resultat beim Seitenwechsel: 
`"syntax error, unexpected token ";"`
Sind solche Vergleichsoperatoren überhaupt möglich?

**Comment by doishub** [comment]
Kann es sein, dass ein Semikolon mit im Bedingungsfeld aufgenommen wurde?
`$feldname <= '10';` <-> `$feldname <= '10'`

**Comment by Shoekrates** [comment]
Nein. Es steht nur die Bedingung im Feld ohne Semikolon.
Das Eingabefeld ist ein normales Input. Kommen da vielleicht die Datentypen durcheinander?

**Comment by doishub** [comment]
Haben wir auch schon drüber nachgedacht. Unsere lokalen Tests führen allerdings gerade immer zum Erfolg. Könntest du einmal folgende Schreibweisen testen:
- `$feldname <= 10`
- `(int) $feldname <= 10`

Und bist du sicher, dass es genau diese Bedingung ist und nicht zufällig eine andere Formularseite aufgerufen wird?

**Comment by Shoekrates** [comment]
Leider in beiden Fällen kein Erfolg. Ich habe das Feld jetzt auch explizit auf type="number" gesetzt: gleiches Ergebnis.

Ich habe gleichzeitig auch die Erweiterung https://github.com/terminal42/contao-conditionalformfields installiert. Kann sich da irgendwas beißen? Diese Erweiterung hat übrigens das gleiche Problem mit kleiner/größer und bereits einen schon länger offenen Issue dazu: https://github.com/terminal42/contao-conditionalformfields/issues/47
Vielleicht bringt euch das auf die Fährte?

**Comment by doishub** [comment]
Hier wird die Bedingung genau so geprüft. Vielleicht lässt sich das Issue direkt mit fixen. Wir schauen uns das mal an.

**Comment by doishub** [comment]
Hallo Christian, ich habe soeben einen fix eingespielt. Könntest du einmal den `dev-main`-Branch installieren und noch einmal testen?

**Comment by Shoekrates** [comment]
Danke für das Update, leider aber keine Besserung. Ich lande immer wieder in dem Syntax Error. Ich habe alle möglichen oben genannten Schreibweisen probiert, auch mal nur > oder < und >= und <=. 
Test auf gleichen Wert (==) funktioniert einwandfrei.

**Comment by doishub** [comment]
Du bekommst exakt den selben Fehler? Das ist merkwürdig, da ich inzwischen eine andere Technik für das Auflösen der Bedingung verwende und diese eigentlich andere Fehlermeldungen liefert. Könntest du mir den Dump für dein Formular zukommen lassen, ich bekomme es gerade leider nicht reproduziert?

**Comment by doishub** [comment]
My bad... Hatte vergessen das Bundle auf Packagist zu aktualisieren. Müsste nun laufen 😉

**Comment by Shoekrates** [comment]
Ja, jetzt funktioniert der Abgleich wie gewollt. Danke!
