### ISSUE TITLE
Advanced Forms doesnt show next page/broken?

### ISSUE THREAD

**Issue by mr2017x** [oveleon/contao-advanced-form#13]
Hi,

when trying to implement Advanced forms it seems there are some bugs in actual 0.2.2 Version

First it is shown as 
Formularseite
### FORMULARSEITE :: SCHRITT 1 - NAME ### 

not as defined as "Seitenumbruch".

Second it is not working anymore.

![image](https://user-images.githubusercontent.com/31145556/170475561-6a0b5b45-4024-4bcb-aca1-cc101bdc8026.png)

is it on website, 

![image](https://user-images.githubusercontent.com/31145556/170475628-56093788-83ec-4cc8-99a9-aadb8fa5a556.png)

at backend, also in the html-code there are no findings. Maybe an issue with contao 4.13.4? PHP 8.1 is in use.

If i can provide further information, just tell me :)

thanks in advance.

**Comment by zoglo** [comment]
@mr2017x We do not support PHP 8.1 yet, could you test it with PHP 8.0?

**Comment by zoglo** [comment]
I can not reproduce this issue on PHP 8.1, it seems to work fine. Could you provide me with your form configuration?
It's also called a form-page as it'll redirect to another page rather than being a page break.

It would also be interesting to see what plugins you installed as some may collide with contao-advanced-form.

Could you also test your configuration on PHP 8.0 and/or 7.4 and tell me if it works?

**Comment by mr2017x** [comment]
Hi Zoglo,

thanks for rapid answer.

Tested it with php 8.0 also, same issue.

Installed modules
contao cms 4.13.4
nature theme 1.9.0
ma3xl3/contao-easy-favicon 2.0.5
Leaflet Maps für Contao 3.2.3
oveleon/contao-company-bundle 1.3.3
Contao Cookiebar 1.12.1
Contao Bewertungen Bundle 1.2.1
Leads 1.4.28
Notification Center 1.6.10

do you have any idea what could disturb the form from running properly?

**Comment by zoglo** [comment]
I always suggest a clean install to see if it works.

All I can think about right now is that you have a normal **Submit field** at the end of your form.

Make sure to remove it as the advanced form uses a formpage for submitting a form.

**Comment by mr2017x** [comment]
OK, that was not clear to me, thanks i will test

**Comment by zoglo** [comment]
@mr2017x Did the solution work for you?
