### ISSUE TITLE
Probleme in der Kombination mit m-vo/contao-nested-forms

### ISSUE THREAD

**Issue by felixpfeiffer** [oveleon/contao-advanced-form#14]
Die Kombination mit den Subformularen schmeißt einen Fehler 500.

Dieser wird wohl in/um die Funktion FormPageManager/createDummyForm() provoziert.

Ich nutze das gaze in Conto 4.13 , php8.1.1

Gruß, Felix

**Comment by zoglo** [comment]
Hi @felixpfeiffer,

sorry wegen der langen Wartezeit.
Könntest du es mal mit dem "dev-develop"-Branch testen ob es weiterhin zu den Fehlern kommt?

**Comment by zoglo** [comment]
@felixpfeiffer Bump

**Comment by zoglo** [comment]
https://github.com/oveleon/contao-advanced-form/releases/tag/0.2.3

**Comment by zoglo** [comment]
The mentioned release should fix the issue as m-vo/contao-nested-forms wasn't part of the issue.
With the new release, these errors should disappear.

You can reopen the issue if you encounter the same error after an update to version 0.2.3
