### ISSUE TITLE
Geschachtelte Abfragen

### ISSUE THREAD

**Issue by bkrmb** [oveleon/contao-advanced-form#15]
Hallo, besteht die Möglichkeit, geschachtelte Abfragen einzubauen? 

Z. B.: Garagentor 1 oder 2 -> Weiß oder Farbig -> Farbauswahl

$Garagentor == 'Sektionaltor-M' and $Farbauswahl-M == 'Color'  leider ohne Funktion

Viele Grüße

Ben

**Comment by doishub** [comment]
Hallo,
ja das sollte gehen. Für die Validierung wird die Expression Language von Symfony verwendet:
https://symfony.com/doc/current/components/expression_language.html

Ich bin mir allerdings unsicher ob Variablen wie `$Farbauswahl-M` valide sind. 
Du könntest folgende Dinge einmal ausprobieren (nur Vermutungen):
- `&&` statt `and` (wobei es keinen Unterschied machen sollte)
- Variable von `$Farbauswahl-M` in `$FarbauswahlM` umbenennen
- Abfrage klammern: `($Garagentor == 'Sektionaltor-M') and ($Farbauswahl-M == 'Color'`)
- Auch die Verwendung der Variablen ohne `$` sollte inzwischen möglich sein

**Comment by bkrmb** [comment]
Hallo, vielen Dank für das Feedback. Leider waren die genannten Lösungsvorschläge ohne Erfolg, so dass ich jetzt die geschachtelte Abfrage rausgenommen habe. Zusätzlich habe ich auch noch die Variablen umbenannt. So läuft jetzt erstmal alles :-)
