### ISSUE TITLE
Conflict with contao-haste 5.10

### ISSUE THREAD

**Issue by tn34de** [oveleon/contao-advanced-form#17]
`oveleon/contao-advanced-form[0.2.3, ..., 0.2.x-dev] require codefog/contao-haste ~4.25 -> found codefog/contao-haste[4.25.0, ..., 4.x-dev] but these were not loaded, likely because it conflicts with another require`

Is there already a timeline for an update with resolves the conflict with "contao-haste 5.10"? I'm relying heavily on terminal42 extensions, which use contao-haste 5.10, but for a specific requirement I desperately need (your) advanced-forms.

Is there anything we can do, to speed up the process?

**Comment by tn34de** [comment]
Resolved with help from Contao Forum.

**Comment by zoglo** [comment]
We do not support Contao Haste 5 as of yet.
It has been unlocked a day ago within the "dev-develop" branch :)

**Comment by tn34de** [comment]
That's the branch you just told me about in the forum. That waorks for now. Thanks!
