### ISSUE TITLE
Field value does not evaluate of following page

### ISSUE THREAD

**Issue by zonky2** [oveleon/contao-advanced-form#18]
same problem as https://github.com/terminal42/contao-conditionalformfields/issues/87#issuecomment-2014812362

**Comment by zoglo** [comment]
@zonky2 did you consider using the in-built conditions as well?

I do understand that mpforms would need CFF, the Advanced form has conditions on each page as well that you could use that don't need to rely on JS.

**Comment by zonky2** [comment]
yes, but this is not about the conditions of the whole page but those of a widget...

I'll see if I can get a PR together

**Comment by zonky2** [comment]
fixed with #19
