### ISSUE TITLE
Feature Request: Autoresponder für advanced_form über Notification Center ermöglichen

### ISSUE THREAD

**Issue by githuppi** [oveleon/contao-advanced-form#3]
Hallo,

wir haben hier einen Fall mit einem 10 seitigen Formular, das umfassende Eingaben aufnimmt. Toll wäre es, wenn diese Eingaben dem Sender als Autoresponder zur Verfügung gestellt werden können. 

**Ist es vielleicht für die Zukunft möglich, die Benachrichtigungsfunktion des Notification Centers an eure Erweiterung zu koppeln?**

Eine Rückmeldung dazu wäre toll.

**Comment by zonky2** [comment]
@githuppi das CAF wird doch über den Formulargenerator erzeugt - gibt es da keine Auswahl für das NC bzw. kommen die Daten dort nicht an?

**Comment by githuppi** [comment]
@zonky2 Hi, ich kann im Menüpunkt „Erweiterte Formulare“ in den Einstellungen keine Benachrichtigung über das NC anwählen. Dort existiert die Option nicht. Auch im Formularfeld, das später für das Senden konfiguriert wird, gibt es diese Auswahl nicht.

**Comment by zonky2** [comment]
> ich kann im Menüpunkt „Erweiterte Formulare“ in den Einstellungen keine Benachrichtigung über das NC anwählen

dort müsste das sein - hmm... o.k. schade :(

**Comment by githuppi** [comment]
@zonky2 das Senden wird in dieser Erweiterung explizit über ein Formular-Element geregelt nicht über die Formular-Einstellungen. Daher müsste eine Benachrichtigung über das NC dann im Element auswählbar gemacht werden.

**Comment by zonky2** [comment]
o.k.!

**Comment by eki89** [comment]
Hallo githuppi,
anhand deiner Angaben sehe ich, dass du leider das veraltete Advanced Form installiert hast, welches ausgrund von Änderung des Contao Core nicht mehr funktioniert (https://github.com/oveleon/contao-advanced-form-bundle).
Die neue Implementierung des Advanced Form nutzt die Standardfunktionalität beim Versenden des Formulars, weswegen hier der native Support für das Notification Center tatsächlich funktioniert.

Leider sind die zwei Erweiterungen nicht miteinander kompatibel, sodass die dieses nicht einfach ersetzen kannst.

Ich würde dir empfehlen, die richtige Erweiterung zu installieren, Formularfelder aus "Erweiterte Formulare" auszuschneiden und in einem normalen Formular einzufügen. Die Formularseiten müssen im normalen Formulargenerator dann als PageSwitch abgebildet werden. Im Anschluss kannst du die veraltete Version löschen. Leider etwas umständlich, eine andere Lösung wird allerdings schwierig.

**Comment by githuppi** [comment]
@eki89 Hi, Installiert ist oveleon/contao-advanced-form-bundle in der Version 0.2.1

**Comment by eki89** [comment]
Richtig wäre oveleon/contao-advanced-form (https://github.com/oveleon/contao-advanced-form).

Versuche das oben von mir beschriebene Vorgehen mal aus. Das sollte sämtliche deiner Probleme lösen. Leider etwas fummelig, aber mit ausschneiden/kopieren und einfügen durchaus schnell machbar.

**Comment by githuppi** [comment]
@eki89 okay alles klar und danke für das Feedback. 

Ich habe mich in der Erweiterungsliste im Contao Manager davon leiten lassen, dass die oveleon/contao-advanced-form-bundle Version häufiger geladen wurde und öfter favorisiert wurde. 

Wenn es sich hierbei um die veraltete Version handelt wäre es schön, wenn ihr das besser kenntlich macht.

**Comment by eki89** [comment]
Das ist richtig. Ich kümmere mich möglichst zeitnah darum, damit diese Version auch gar nicht mehr für Contao 4.9 und höher installierbar ist. Momentan ist diese Information lediglich in GitHub sichtbar.

**Comment by zoglo** [comment]
Closed as resolved -> Bundles was updated via contao/package-metadata (Old bundle was archived)
