### ISSUE TITLE
Form could not be sent: Expected response code 250 but got code "553", with message "553 5.7.1 <mail@domain.de>: Sender address rejected: not owned by user m041c27a

### ISSUE THREAD

**Issue by githuppi** [oveleon/contao-advanced-form#4]
Beim Versenden einer advanced-form erhalte ich den nachfolgenden Fehler:

**Form could not be sent: Expected response code 250 but got code "553", with message "553 5.7.1 <mail@domain.de>: Sender address rejected: not owned by user m041c27a**

mail@domain.de habe ich aus Datenschutzgründen geändert.

Die E-Mail-Adresse des Webseiten-Administrators (in der Seitenstruktur) sollte doch eigentlich zum Versenden verwendet werden. Soweit ich das sehe wird jedoch die E-Mail-Adresse des Systemadministrators (in den Contao Einstellungen) zum Versenden verwendet.

Heißt wenn ich in den Einstellungen die gleiche Adresse vom Domaininhaber hinterlege gelingt der Versand ohne Fehler.

**Handelt es sich hier evtl. um einen Fehler beim Heranziehen der festgelegten E-Mail in den Contao Einstellungen?**

**Comment by eki89** [comment]
Welches Advanced Form hast du genau installiert?
- https://github.com/oveleon/contao-advanced-form
- https://github.com/oveleon/contao-advanced-form-bundle

Ersteres nutzt die gesamte Technik des normalen Contao Formulargenerators, sodass ein Großteil von Erweiterungen, die den Contao Formulargenerator erweitern, mit dem Advanced Form kompatibel sind (Notification Center, Ajax Forms, etc.)

**Comment by githuppi** [comment]
Installiert ist oveleon/contao-advanced-form-bundle in der Version 0.2.1

**Comment by eki89** [comment]
Duplicate: https://github.com/oveleon/contao-advanced-form/issues/3
