### ISSUE TITLE
Feature: Fortschritt im Formular anzeigen -> Progressbar / Fortschrittsbalken

### ISSUE THREAD

**Issue by githuppi** [oveleon/contao-advanced-form#5]
Hallo,

in der vorherigen Version von advanced-form ließ sich der Fortschritt des Formulares einfach visuell abbilden. Ist es möglich in der neuen Version ebenfalls eine „Progressbar“ einen Fortschrittsbalken einzublenden?

Ich freue mich auf Feedback dazu.

**Comment by eki89** [comment]
Der Fortschrittsbalken lässt sich leider nicht wirklich gut berechnen, weswegen es dieser nicht mehr ins Advanced Form geschafft hat. Persönlich bilden wir den Fortschrittsbalken mittlerweile mit einem einfachen HTML-Widget ab, welches wir zu Beginn jeder Formularseite einbinden und natürlich entsprechend durchstylen.

**Comment by githuppi** [comment]
@eki89 danke für den Hinweis, hab es jetzt auch so gelöst.
