### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by petrad** [oveleon/contao-advanced-form#6]
jegliche Version führt zu folgendem Error mit PHP 7.4 und Contao 4.9:

`request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function registerFieldsets() on null" at /..../vendor/oveleon/contao-advanced-form/src/Resources/contao/classes/FormPageManager.php line 156 {"exception":"[object] (Error(code: 0): Call to a member function registerFieldsets() on null at /.../vendor/oveleon/contao-advanced-form/src/Resources/contao/classes/FormPageManager.php:156)"} []`

LG, Petra

**Comment by zoglo** [comment]
Hi @petrad,

es scheint, als würde eine andere Erweiterung den Hook "compileFormFields" nutzen, in welchem es zu besagtem Fehler kommt.
Die Funktion registerFieldsets() kommt nicht aus dem AdvancedForm, hier muss es sich um eine andere Erweiterung handeln.

Könntest du uns deine composer.json zukommen lassen?

**Comment by petrad** [comment]
Hallo @zoglo,

vielen Dank für Deine schnelle Rückmeldung. Die composer.json ist lang, daher habe ich die Recherche vorweggenommen. In der Tat hat das folgende Modul ebenfalls die Hook-Bezeichnung "compileFormFields": 
[https://github.com/terminal42/contao-conditionalformfields/search?q=compileFormFields](url)

Was macht man denn jetzt?

LG, Petra

**Comment by zoglo** [comment]
Könntest du das AdvancedForm einmal deinstallieren und schauen, ob der Fehler immer noch auftritt?

**Comment by petrad** [comment]
Hallo @zoglo,
dann erscheint der Fehler nicht mehr.

LG, Petra

**Comment by zoglo** [comment]
Okay, der Fehler liegt definitiv bei uns,
 
hierbei liegt es daran, dass die Hooks, welche wir im AdvancedForm benutzen, dieselbe Benennung wie in Contao haben.
Diese müssten angepasst werden, damit andere Plugins, welche auf die Contao-Hooks zugreifen, nicht mit unserem Plugin kollidieren. Wir versuchen den Fehler zeitnah zu beheben.

**Comment by petrad** [comment]
Hallo @zoglo,

da ich Eure Erweiterung jetzt benötige und ConditionalFormFields installiert bleiben muss, eine Frage: Würde es nicht erst einmal ausreichen, in der FormPageManager.php in Zeile 156 folgendes abzufragen: 

```
if($callback[0]!="ConditionalFormFields"):
    $arrFormFields = $objCallback->{$callback[0]}->{$callback[1]}($arrFormFields, $this->getFormId(), $form);
endif;
```

Ein Test hat ergeben, dass ConditionalFormFields trotzdem noch funktioniert.

LG, Petra

**Comment by zoglo** [comment]
Hallo @petrad ,

mit der neuen Version funktioniert das AdvancedForm auch mit ConditionalFormFields.
Magst du es nochmal in deiner Instanz testen?

**Comment by petrad** [comment]
Vielen Dank @zoglo für Deinen Hinweis! Die Kundenwebsite läuft mittlerweile ohne conditionalformfields, die würde ich ungern wieder ändern...aber vielleicht wird es mal bei einer anderen Seite benötigt :)
