### ISSUE TITLE
php 8 kompat.

### ISSUE THREAD

**Issue by bubaks** [oveleon/contao-advanced-form#7]
hallo super form bundle :) allerdings habe ich da eine frage kann man das auch mit php8 nutzen?
danke
grüße

**Comment by zonky2** [comment]
lt composer.json nicht https://github.com/oveleon/contao-advanced-form/blob/612e5793f6ab7c83002dadb9e365dc83696371a2/composer.json#L26

bedeutet aber nicht zwangsweise, das es nicht geht...

**Comment by bubaks** [comment]
danke für die schnelle info :)
leider erhalte ich diese ausgabe
In InitCommand.php line 909:
                                                                               
  Package oveleon/contao-advanced-form has requirements incompatible with you  
  r PHP version, PHP extensions and Composer version:                          
    - oveleon/contao-advanced-form 0.1.1 requires php ^7.2 which does not mat  
  ch your installed version 8.0.14.                                            
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [...]


 Process terminated with exit code 1
 Result: General error

**Comment by zonky2** [comment]
öhmm... steht doch da was das Problem ist

> Package oveleon/contao-advanced-form has **requirements incompatible with your PHP version**, PHP extensions and Composer version:
>- oveleon/contao-advanced-form 0.1.1 requires php ^7.2 which does not match your installed version 8.0.14.

Du hast 8.0.14 - gefordert ist ab 7.2 (aber kleiner als 8)

Ein Weg: mach einen Fork, ändere die Angabe auf `"php":"^7.2 || ^8.0",` und installiere Deinen Fork

**Comment by bubaks** [comment]
ahh ok danke versuche ich gleich muss noch rausfinden wie man ohne manager das installiert :) bin da noch nicht so fit auf dem gebiet :) haha

**Comment by zonky2** [comment]
geht auch mit Manager... musst nur vorher die composer.json anpassen

guck mal hier das zweite Beispiel: https://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen

**Comment by bubaks** [comment]
:( das verstehe ich leider nicht haha habe dann etwas anderes versucht
den form ordner hoch geladen in den /oveleon/contao-advanced-form 
die composer
"require":{
    "php":"^7.2 || ^8.0",
    geändert auch mal nur ^8.0 oder >=7.2 versucht 
dann wird mir das paket im manager angezeigt und beim installieren kommt dann wieder die info
oveleon/contao-advanced-form 0.1.1 requires php ^7.2 which does not match your installed version 8.0.14.
schade das ich da zu dumm bin

**Comment by bubaks** [comment]
wollte mal versuchen auf php 7.4 zu drücken dann funkt contao nicht mehr und die auto.rep. im manager bleibt auch stecken

**Comment by zonky2** [comment]
in Deinem vendor-Ordner kannst Du das nicht einfach ändern - da ist es für die Prüfung, die der composer macht, zu spät...

Du muss in der composer.json Deinen Fork laden lassen - analog dem Beispiel von MM

in Zeile 18 muss dann die URL zu **deinem** Fork

wo ist der?!?! https://github.com/bubaks?tab=repositories

**Comment by zonky2** [comment]
ansonsten: https://www.google.com/search?q=composer+load+your+own+fork

btw: das alles gehört eher ins Forum als in die Issues

**Comment by bubaks** [comment]
ok na bumm das versuche ich gleich danke für die hilfe und lern stunde sorry bin auch auf git neu (wieder einer der keine ahnung hat) haha

**Comment by zonky2** [comment]
hier auf der Seite ist oben rechts "Fork" - damit ziehst Du eine Kopie in Deinen Account - dort kannst Du schalten und walten wie du möchtest (kleine Sachen direkt online oder mit einer IDE wie z.B. SourceTree) - dann eben Deine Änderungen über die composer.json laden lassen ... siehe Google Links

**Comment by zonky2** [comment]
wenn Du composer auf der Konsole ausführst, könnte man auch den Parameter `--ignore-platform-reqs` probieren - habe ich aber noch nie getestet... dann brauchst Du keinen Fork

Tipps Konsole hier: https://metamodels.readthedocs.io/de/latest/cookbook/symfony/mm-2-1-tips.html#composer-update

**Comment by bubaks** [comment]
wow du bist super danke die hilfe ist echt spitze! hab schon gerätselt wie ich die zip datei da hoch bekomme das es so einfach ist haha naja schäme mich

**Comment by bubaks** [comment]
nee leider das geht alles nicht :(
die url hab ich in verschiedenen möglichkeiten versucht fehler von nicht gefunden etc 

  Problem 1
    - Root composer.json requires bubaks/contao-advanced-form, it could not be found in any version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
[1637.2MiB/31.79s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>

und einige andere bis zu error 500...

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/bubaks/contao-advanced-form.git"
        }
    ]

    "require": {
...
        "oveleon/contao-cookiebar": "^1.9",
	"bubaks/contao-advanced-form": "^0.1.1",

wenn ich oveleon/contao-advanced-form eingebe lädt er obwohl die url nicht geändert scheinbar das original von euch dann kommt wieder der php 8 fehler 
...
    }

schade habe auch deine links studiert und danach versucht leider nichts positives
im forum nutzt das scheinbar niemand habe dazu leider nichts gefunden schade ist ja ein super form 
danke dennoch für deine schnelle hilfe

**Comment by zonky2** [comment]
> im forum nutzt das scheinbar niemand habe dazu leider nichts gefunden schade ist ja ein super form

weil noch recht viele  Erweiterungen nicht auf PHP 8 ungestellt/freigegeben wurden...

mach doch bitte im Forum bei den Erweiterungen einen eigenen Thread auf - verlinke auf das Issue und poste dort Deine komplette(!) composer.json (bitte im Editor das "PHP-Icon" verwenden!)

anschließend Link hier rein posten

**Comment by zonky2** [comment]
müsste m.E. so sein
`"bubaks/contao-advanced-form": "dev-master as 0.1.1",`

**Comment by bubaks** [comment]
ok danke das versuche ich und forum werde ich auch machen mein erster thread :) aber das alles morgen jetzt wünsche ich einen Guten Rutsch in neue Jahr! :)

**Comment by bubaks** [comment]
hi nach weiteren 6h gebe ich auf
mit `"oveleon/contao-advanced-form": "dev-master as 0.1.1",` hat er zwar den fork instaliert allerdings kommen dann beim aufruf von installtool fehler..
hast du vielleicht noch eine idee wie man von php8 auf 7 wieder runter kommt ?
habe dem manager gesagt php 7 domain umgestellt auf 7 aber sobald man das install tool aufruft kommt
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". 
leider finde ich keine datei wo ist das ändern kann 
composer update,cache löschen alles kein erfolg 
danke für deine hilfe

**Comment by zonky2** [comment]
>mach doch bitte im Forum bei den Erweiterungen einen eigenen Thread auf - verlinke auf das Issue und poste dort Deine komplette(!) composer.json (bitte im Editor das "PHP-Icon" verwenden!)

> anschließend Link hier rein posten

**Comment by bubaks** [comment]
hier der link zum forum

[https://community.contao.org/de/showthread.php?82237-ovelon-contao-advanced-form-und-PHP-8](https://community.contao.org/de/showthread.php?82237-ovelon-contao-advanced-form-und-PHP-8)

**Comment by zonky2** [comment]
@bubaks warum hast Du das Issue geschlossen - ist ja noch nicht gefixt!

**Comment by bubaks** [comment]
zack ist schon wieder offen
dachte weil das wie im forum geschrieben ja nicht an dem modul liegt kann ich das schließen 
mit der änderung in der composer und dem fork kann man es installieren

**Comment by zonky2** [comment]
> mit der Änderung in der composer und dem Fork kann man es installieren

Ziel ist aber nicht, dass jeder seinen eigenen Fork macht ;-)

**Comment by zoglo** [comment]
Hallo @bubaks ,

zurzeit gibt es für das Bundle noch keinen PHP8 Support. Leider reicht das alleinige Anheben der PHP-Version nicht aus, sodass hier am Code nachgearbeitet werden muss. 
Wie bereits im Forum von Doi erwähnt, kümmern wir uns die nächsten Tage um den PHP8 Support.

Bezüglich des Fehlers im Contao-Forum: Hier sieht es stark danach aus, dass es an Haste liegt.

Unter welcher Contao Version tritt der Fehler denn auf?

**Comment by bubaks** [comment]
Hallo
Ja keinen Stress... bin vermutlich der einzige der leider PHP8 installiert hat...
wollte nur etwas sehr feines Nutzen statt normal Formular :) haha
alle Tests mit Contao Version 4.12.5

seltsam war das die Haste fehler nicht beim Webhosting aufgetreten sind leider habe ich keinen Unterschied gefunden wird es aber sicher geben..
ich habe auch mit dem Modul von terminal versucht da eine ältere Version von Haste genutzt wird aber leider auch Fehler 
wie beschrieben

**Comment by zoglo** [comment]
Hey @bubaks , 
wir haben das AdvancedForm auf PHP8 angehoben. Magst du hier einmal sagen, ob es für dich funktioniert?
